name: Python Selenium Job

on:
  workflow_dispatch:
  schedule:
    # 매일 자정에 실행
    - cron: '10 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium firebase-admin webdriver-manager
    
    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        if [ ! -f /usr/bin/chromedriver ]; then
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        fi
    
    - name: Run Selenium script
      run: python scraper.py
